In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
bike=pd.read_csv("C:\\new project 11\\bike-repo\\data\\all_bikez_raw.csv")

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\1490246197.py:1: DtypeWarning: Columns (80,81) have mixed types. Specify dtype option on import or set low_memory=False.
  bike=pd.read_csv("C:\\new project 11\\bike-repo\\data\\all_bikez_raw.csv")

In [7]:
bike.head(5)

,Model,Year,Category,Rating,Displacement,Engine type,Engine details,Power,Top speed,Bore x stroke,...,Emission details,Rear percentage of weight,Oil filter,Battery,Belt teeth,Belt width,Pulley teeth,Chain size,Factory warranty,Service interval
0,AJP GALP 50 Enduro,2005,Enduro / offroad,3.7 Check out the detailed rating of off-roa...,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",NaN,9.5 HP (6.9 kW)),NaN,40.0 x 39.7 mm (1.6 x 1.6 inches),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AJP GALP 50 R,2005,Sport,3.6 Check out the detailed rating of racing ...,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",NaN,9.5 HP (6.9 kW)),NaN,40.0 x 39.7 mm (1.6 x 1.6 inches),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AJP GALP 50 Supermotard,2005,Super motard,1.9 Check out the detailed rating of off-roa...,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",NaN,9.5 HP (6.9 kW)),NaN,40.0 x 39.7 mm (1.6 x 1.6 inches),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AJP PR3 125 Enduro,2015,Enduro / offroad,2.1 Check out the detailed rating of off-roa...,124.0 ccm (7.57 cubic inches),"Single cylinder, four-stroke",NaN,12.5 HP (9.1 kW)) @ 12600 RPM,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AJP PR3 125 Enduro Pro,2015,Enduro / offroad,Do you know this bike?Click here to rate it. W...,124.0 ccm (7.57 cubic inches),"Single cylinder, four-stroke",NaN,12.5 HP (9.1 kW)) @ 12600 RPM,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
bike.shape

(38472, 85)

In [9]:
bike.columns

Index(['Model', 'Year', 'Category', 'Rating', 'Displacement', 'Engine type',
       'Engine details', 'Power', 'Top speed', 'Bore x stroke', 'Fuel system',
       'Ignition', 'Cooling system', 'Gearbox', 'Transmission type',
       'Driveline', 'Frame type', 'Front suspension', 'Rear suspension',
       'Wheels', 'Seat', 'Dry weight', 'Power/weight ratio', 'Clutch',
       'Overall width', 'Fuel capacity', 'Comments', 'Exhaust system',
       'Compression', 'Fuel control', 'Lubrication system', 'Front tire',
       'Rear tire', 'Front brakes', 'Rear brakes',
       'Weight incl. oil, gas, etc', 'Overall length', 'Ground clearance',
       'Wheelbase', 'Oil capacity', 'Color options', 'Starter', 'Electrical',
       'Valves per cylinder', 'Diameter', 'Carrying capacity',
       'Modifications compared to previous model', 'Seat height',
       'Overall height', 'Fuel consumption', 'Greenhouse gases', 'Torque',
       'Max RPM', 'Light', 'Alternate seat height', 'Rake (fork angle)',
       '0-100 km/h (0-62 mph)', 'Front wheel travel', 'Rear wheel travel',
       'Engine oil', 'Instruments', '60-140 km/h (37-87 mph), highest gear',
       'Front percentage of weight', 'Trail', 'Brake fluid', 'Coolant',
       'Spark plugs', 'Idle speed', 'Tire pressure front',
       'Tire pressure rear', 'Fork tube size', 'Chain links', 'Sprockets',
       'Reserve fuel capacity', '1/4 mile (0.4 km)', 'Emission details',
       'Rear percentage of weight', 'Oil filter', 'Battery', 'Belt teeth',
       'Belt width', 'Pulley teeth', 'Chain size', 'Factory warranty',
       'Service interval'],
      dtype='object')

In [10]:
bike.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38472 entries, 0 to 38471
Data columns (total 85 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Model                                     38472 non-null  object
 1   Year                                      38472 non-null  int64
 2   Category                                  38472 non-null  object
 3   Rating                                    38472 non-null  object
 4   Displacement                              37461 non-null  object
 5   Engine type                               38461 non-null  object
 6   Engine details                            6390 non-null   object
 7   Power                                     26110 non-null  object
 8   Top speed                                 12730 non-null  object
 9   Bore x stroke                             28689 non-null  object
 10  Fuel system                               27844 non-null  object
 11  Ignition                                  16529 non-null  object
 12  Cooling system                            34258 non-null  object
 13  Gearbox                                   32675 non-null  object
 14  Transmission type                         32861 non-null  object
 15  Driveline                                 8324 non-null   object
 16  Frame type                                17303 non-null  object
 17  Front suspension                          26107 non-null  object
 18  Rear suspension                           25540 non-null  object
 19  Wheels                                    9387 non-null   object
 20  Seat                                      4846 non-null   object
 21  Dry weight                                22483 non-null  object
 22  Power/weight ratio                        15213 non-null  object
 23  Clutch                                    15152 non-null  object
 24  Overall width                             18738 non-null  object
 25  Fuel capacity                             31704 non-null  object
 26  Comments                                  13700 non-null  object
 27  Exhaust system                            5900 non-null   object
 28  Compression                               23405 non-null  object
 29  Fuel control                              22008 non-null  object
 30  Lubrication system                        10158 non-null  object
 31  Front tire                                31982 non-null  object
 32  Rear tire                                 32008 non-null  object
 33  Front brakes                              36889 non-null  object
 34  Rear brakes                               36696 non-null  object
 35  Weight incl. oil, gas, etc                14994 non-null  object
 36  Overall length                            22242 non-null  object
 37  Ground clearance                          14205 non-null  object
 38  Wheelbase                                 25493 non-null  object
 39  Oil capacity                              3786 non-null   object
 40  Color options                             24327 non-null  object
 41  Starter                                   26845 non-null  object
 42  Electrical                                3085 non-null   object
 43  Valves per cylinder                       16173 non-null  float64
 44  Diameter                                  18816 non-null  object
 45  Carrying capacity                         2702 non-null   object
 46  Modifications compared to previous model  344 non-null    object
 47  Seat height                               24182 non-null  object
 48  Overall height                            16635 non-null  object
 49  Fuel consumption                          6176 non-null   object
 50  Greenhouse gases                          6176 non-null   object
 51  Torque                                    16634 non-null  object
 52  Max RPM                                   663 non-null    float64
 53  Light                                     3188 non-null   object
 54  Alternate seat height                     841 non-null    object
 55  Rake (fork angle)                         9518 non-null   object
 56  0-100 km/h (0-62 mph)                     424 non-null    object
 57  Front wheel travel                        12233 non-null  object
 58  Rear wheel travel                         11896 non-null  object
 59  Engine oil                                250 non-null    object
 60  Instruments                               4295 non-null   object
 61  60-140 km/h (37-87 mph), highest gear     148 non-null    object
 62  Front percentage of weight                196 non-null    float64
 63  Trail                                     7578 non-null   object
 64  Brake fluid                               244 non-null    object
 65  Coolant                                   126 non-null    object
 66  Spark plugs                               257 non-null    object
 67  Idle speed                                204 non-null    object
 68  Tire pressure front                       198 non-null    object
 69  Tire pressure rear                        198 non-null    object
 70  Fork tube size                            243 non-null    object
 71  Chain links                               133 non-null    float64
 72  Sprockets                                 168 non-null    object
 73  Reserve fuel capacity                     3421 non-null   object
 74  1/4 mile (0.4 km)                         89 non-null     object
 75  Emission details                          4041 non-null   object
 76  Rear percentage of weight                 55 non-null     float64
 77  Oil filter                                113 non-null    object
 78  Battery                                   139 non-null    object
 79  Belt teeth                                39 non-null     float64
 80  Belt width                                36 non-null     object
 81  Pulley teeth                              34 non-null     object
 82  Chain size                                116 non-null    float64
 83  Factory warranty                          5417 non-null   object
 84  Service interval                          61 non-null     object
dtypes: float64(7), int64(1), object(77)
memory usage: 24.9+ MB

In [11]:
bike.describe()

,Year,Valves per cylinder,Max RPM,Front percentage of weight,Chain links,Rear percentage of weight,Belt teeth,Chain size
count,38472.000000,16173.000000,663.000000,196.000000,133.000000,55.000000,39.000000,116.000000
mean,2003.195883,3.680208,11386.953243,56.532653,112.052632,50.741818,135.538462,520.612069
std,20.083372,44.115605,5832.669173,27.973419,7.954716,6.752357,5.129102,26.843758
min,1894.000000,1.000000,3000.000000,30.000000,78.000000,20.000000,128.000000,420.000000
25%,2000.000000,2.000000,9000.000000,46.800000,108.000000,49.000000,133.000000,520.000000
50%,2010.000000,4.000000,11000.000000,48.650000,114.000000,50.000000,135.000000,525.000000
75%,2016.000000,4.000000,13000.000000,50.600000,116.000000,53.000000,138.000000,525.000000
max,2022.000000,5599.000000,54000.000000,175.000000,134.000000,70.000000,152.000000,630.000000

In [12]:
bike.tail()

,Model,Year,Category,Rating,Displacement,Engine type,Engine details,Power,Top speed,Bore x stroke,...,Emission details,Rear percentage of weight,Oil filter,Battery,Belt teeth,Belt width,Pulley teeth,Chain size,Factory warranty,Service interval
38467,emco Sport Novum S 3000 Blei-Gel,2015,Scooter,Do you know this bike?Click here to rate it. W...,NaN,Electric,NaN,4.0 HP (2.9 kW)),65.0 km/h (40.4 mph),NaN,...,No direct emissions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38468,emco Sport Novum S 5000,2015,Scooter,Do you know this bike?Click here to rate it. W...,NaN,Electric,NaN,6.7 HP (4.9 kW)),82.0 km/h (51.0 mph),NaN,...,No direct emissions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38469,proEco Emil,2013,Scooter,Do you know this bike?Click here to rate it. W...,NaN,Electric,Wheel hub motor,2.7 HP (2.0 kW)),45.0 km/h (28.0 mph),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38470,proEco Emilia,2013,Scooter,Do you know this bike?Click here to rate it. W...,NaN,Electric,NaN,2.7 HP (2.0 kW)),45.0 km/h (28.0 mph),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38471,proEco Emma,2013,Scooter,Do you know this bike?Click here to rate it. W...,NaN,Electric,Wheel hub motor,2.7 HP (2.0 kW)),45.0 km/h (28.0 mph),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
bike.isnull().sum()

Model                   0
Year                    0
Category                0
Rating                  0
Displacement         1011
                    ...
Belt width          38436
Pulley teeth        38438
Chain size          38356
Factory warranty    33055
Service interval    38411
Length: 85, dtype: int64

In [14]:
bike.drop(columns=["Belt width", "Pulley teeth", "Chain size", "Factory warranty", "Service interval"], inplace=True)

In [15]:
bike.shape

(38472, 80)

In [16]:
bike.isnull().sum()

Model                            0
Year                             0
Category                         0
Rating                           0
Displacement                  1011
                             ...
Emission details             34431
Rear percentage of weight    38417
Oil filter                   38359
Battery                      38333
Belt teeth                   38433
Length: 80, dtype: int64

In [17]:
# Keep columns that have at least 70% non-null values
# (This drops columns with more than 30% missing values)
threshold = int(0.70 * len(bike))
bike_cleaned  = bike.dropna(thresh=threshold, axis=1)

In [18]:
bike_cleaned.shape

(38472, 16)

In [19]:
bike_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38472 entries, 0 to 38471
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Model              38472 non-null  object
 1   Year               38472 non-null  int64
 2   Category           38472 non-null  object
 3   Rating             38472 non-null  object
 4   Displacement       37461 non-null  object
 5   Engine type        38461 non-null  object
 6   Bore x stroke      28689 non-null  object
 7   Fuel system        27844 non-null  object
 8   Cooling system     34258 non-null  object
 9   Gearbox            32675 non-null  object
 10  Transmission type  32861 non-null  object
 11  Fuel capacity      31704 non-null  object
 12  Front tire         31982 non-null  object
 13  Rear tire          32008 non-null  object
 14  Front brakes       36889 non-null  object
 15  Rear brakes        36696 non-null  object
dtypes: int64(1), object(15)
memory usage: 4.7+ MB

In [20]:
bike_cleaned.drop(columns="Rating", inplace=True)

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\2045411888.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned.drop(columns="Rating", inplace=True)

In [21]:
bike_cleaned.drop(columns="Year", inplace=True)

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\2530966927.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned.drop(columns="Year", inplace=True)

In [22]:
bike_cleaned.head(5)

,Model,Category,Displacement,Engine type,Bore x stroke,Fuel system,Cooling system,Gearbox,Transmission type,Fuel capacity,Front tire,Rear tire,Front brakes,Rear brakes
0,AJP GALP 50 Enduro,Enduro / offroad,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50 litres (1.98 US gallons),80/90-21,110/80-18,Single disc,Single disc
1,AJP GALP 50 R,Sport,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50 litres (1.98 US gallons),130/80-17,130/70-17,Single disc,Single disc
2,AJP GALP 50 Supermotard,Super motard,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50 litres (1.98 US gallons),100/80-17,130/70-17,Single disc,Single disc
3,AJP PR3 125 Enduro,Enduro / offroad,124.0 ccm (7.57 cubic inches),"Single cylinder, four-stroke",NaN,Carburettor. Walbro 30 mm,Air,5-speed,Chain (final drive),7.50 litres (1.98 US gallons),70/100-19,100/100-17,Single disc. 2 piston caliper,Single disc
4,AJP PR3 125 Enduro Pro,Enduro / offroad,124.0 ccm (7.57 cubic inches),"Single cylinder, four-stroke",NaN,Carburettor. Walbro 30 mm,Air,5-speed,Chain (final drive),7.50 litres (1.98 US gallons),70/100-19,100/100-17,Single disc. 2 piston caliper,Single disc

In [23]:
bike_cleaned.isnull().sum()

Model                    0
Category                 0
Displacement          1011
Engine type             11
Bore x stroke         9783
Fuel system          10628
Cooling system        4214
Gearbox               5797
Transmission type     5611
Fuel capacity         6768
Front tire            6490
Rear tire             6464
Front brakes          1583
Rear brakes           1776
dtype: int64

removing all null  value rows

In [24]:
bike_cleaned.dropna(axis=0).isnull().sum()

Model                0
Category             0
Displacement         0
Engine type          0
Bore x stroke        0
Fuel system          0
Cooling system       0
Gearbox              0
Transmission type    0
Fuel capacity        0
Front tire           0
Rear tire            0
Front brakes         0
Rear brakes          0
dtype: int64

# dataframe will no null values

In [25]:
bike_cleaned_df=bike_cleaned.dropna(axis=0)

In [26]:
bike_cleaned_df.isnull().sum()

Model                0
Category             0
Displacement         0
Engine type          0
Bore x stroke        0
Fuel system          0
Cooling system       0
Gearbox              0
Transmission type    0
Fuel capacity        0
Front tire           0
Rear tire            0
Front brakes         0
Rear brakes          0
dtype: int64

In [27]:
bike_cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16040 entries, 0 to 38436
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Model              16040 non-null  object
 1   Category           16040 non-null  object
 2   Displacement       16040 non-null  object
 3   Engine type        16040 non-null  object
 4   Bore x stroke      16040 non-null  object
 5   Fuel system        16040 non-null  object
 6   Cooling system     16040 non-null  object
 7   Gearbox            16040 non-null  object
 8   Transmission type  16040 non-null  object
 9   Fuel capacity      16040 non-null  object
 10  Front tire         16040 non-null  object
 11  Rear tire          16040 non-null  object
 12  Front brakes       16040 non-null  object
 13  Rear brakes        16040 non-null  object
dtypes: object(14)
memory usage: 1.8+ MB

In [28]:
for i in bike_cleaned_df.columns:
    print(i+":")
    print(i, bike_cleaned_df[i].unique())
    print()

Model:
Model ['AJP GALP 50 Enduro' 'AJP GALP 50 R' 'AJP GALP 50 Supermotard' ...
 'Zündapp KS 50 Super Sport type 517-20' 'Zündapp KS 601' 'Zündapp Z 249']

Category:
Category ['Enduro / offroad' 'Sport' 'Super motard' 'Cross / motocross'
 'Prototype / concept model' 'Allround' 'Scooter' 'Custom / cruiser'
 'Classic' 'Naked bike' 'Minibike, sport' 'ATV' 'Touring' 'Sport touring'
 'Trial' 'Minibike, cross' 'Unspecified category']

Displacement:
Displacement ['49.9 ccm (3.04 cubic inches)' '124.0 ccm (7.57 cubic inches)'
 '233.0 ccm (14.22 cubic inches)' '125.0 ccm (7.63 cubic inches)'
 '249.0 ccm (15.19 cubic inches)' '659.7 ccm (40.25 cubic inches)'
 '600.0 ccm (36.61 cubic inches)' '198.2 ccm (12.09 cubic inches)'
 '297.6 ccm (18.16 cubic inches)' '501.0 ccm (30.57 cubic inches)'
 '124.6 ccm (7.60 cubic inches)' '40.0 ccm (2.44 cubic inches)'
 '49.0 ccm (2.99 cubic inches)' '320.0 ccm (19.53 cubic inches)'
 '124.5 ccm (7.60 cubic inches)' '49.3 ccm (3.01 cubic inches)'
 '248.0 ccm (15.13 cubic inches)' '348.0 ccm (21.23 cubic inches)'
 '347.0 ccm (21.17 cubic inches)' '498.0 ccm (30.39 cubic inches)'
 '593.0 ccm (36.18 cubic inches)' '646.0 ccm (39.42 cubic inches)'
 '234.0 ccm (14.28 cubic inches)' '247.0 ccm (15.07 cubic inches)'
 '562.0 ccm (34.29 cubic inches)' '647.0 ccm (39.48 cubic inches)'
 '171.2 ccm (10.45 cubic inches)' '100.0 ccm (6.10 cubic inches)'
 '250.0 ccm (15.26 cubic inches)' '95.6 ccm (5.83 cubic inches)'
 '346.0 ccm (21.11 cubic inches)' '124.9 ccm (7.62 cubic inches)'
 '169.0 ccm (10.31 cubic inches)' '196.0 ccm (11.96 cubic inches)'
 '272.3 ccm (16.62 cubic inches)' '565.0 ccm (34.48 cubic inches)'
 '149.8 ccm (9.14 cubic inches)' '313.0 ccm (19.10 cubic inches)'
 '149.0 ccm (9.09 cubic inches)' '150.1 ccm (9.16 cubic inches)'
 '150.0 ccm (9.15 cubic inches)' '96.0 ccm (5.86 cubic inches)'
 '246.2 ccm (15.02 cubic inches)' '174.2 ccm (10.63 cubic inches)'
 '246.0 ccm (15.01 cubic inches)' '123.0 ccm (7.51 cubic inches)'
 '249.8 ccm (15.24 cubic inches)' '1600.0 ccm (97.63 cubic inches)'
 '244.0 ccm (14.89 cubic inches)' '399.0 ccm (24.35 cubic inches)'
 '459.0 ccm (28.01 cubic inches)' '460.0 ccm (28.07 cubic inches)'
 '1197.0 ccm (73.04 cubic inches)' '997.6 ccm (60.87 cubic inches)'
 '997.0 ccm (60.84 cubic inches)' '998.0 ccm (60.90 cubic inches)'
 '124.8 ccm (7.62 cubic inches)' '749.9 ccm (45.76 cubic inches)'
 '900.0 ccm (54.92 cubic inches)' '896.0 ccm (54.67 cubic inches)'
 '896.1 ccm (54.68 cubic inches)' '49.7 ccm (3.03 cubic inches)'
 '449.0 ccm (27.40 cubic inches)' '893.0 ccm (54.49 cubic inches)'
 '839.0 ccm (51.20 cubic inches)' '839.3 ccm (51.21 cubic inches)'
 '49.4 ccm (3.01 cubic inches)' '652.0 ccm (39.79 cubic inches)'
 '660.0 ccm (40.27 cubic inches)' '659.0 ccm (40.21 cubic inches)'
 '651.8 ccm (39.77 cubic inches)' '124.2 ccm (7.58 cubic inches)'
 '50.0 ccm (3.05 cubic inches)' '999.6 ccm (61.00 cubic inches)'
 '1099.0 ccm (67.06 cubic inches)' '1078.0 ccm (65.78 cubic inches)'
 '998.2 ccm (60.91 cubic inches)' '160.0 ccm (9.76 cubic inches)'
 '174.0 ccm (10.62 cubic inches)' '278.0 ccm (16.96 cubic inches)'
 '122.0 ccm (7.44 cubic inches)' '549.0 ccm (33.50 cubic inches)'
 '99.0 ccm (6.04 cubic inches)' '96.2 ccm (5.87 cubic inches)'
 '180.8 ccm (11.03 cubic inches)' '180.0 ccm (10.98 cubic inches)'
 '181.0 ccm (11.04 cubic inches)' '278.3 ccm (16.98 cubic inches)'
 '493.0 ccm (30.08 cubic inches)' '749.0 ccm (45.70 cubic inches)'
 '197.9 ccm (12.08 cubic inches)' '244.3 ccm (14.91 cubic inches)'
 '49.2 ccm (3.00 cubic inches)' '198.0 ccm (12.08 cubic inches)'
 '244.9 ccm (14.94 cubic inches)' '1077.0 ccm (65.72 cubic inches)'
 '999.0 ccm (60.96 cubic inches)' '951.0 ccm (58.03 cubic inches)'
 '270.0 ccm (16.48 cubic inches)' '366.0 ccm (22.33 cubic inches)'
 '443.0 ccm (27.03 cubic inches)' '545.0 ccm (33.26 cubic inches)'
 '641.0 ccm (39.11 cubic inches)' '695.0 ccm (42.41 cubic inches)'
 '90.0 ccm (5.49 cubic inches)' '433.0 ccm (26.42 cubic inches)'
 '543.0 ccm (33.13 cubic inches)' '686.0 ccm (41.86 cubic inches)'
 '445.0 ccm (27.15 cubic inches)' '194.0 ccm (11.84 cubic inches)'
 '342.0 ccm (20.87 cubic inches)' '601.0 ccm (36.67 cubic inches)'
 '995.0 ccm (60.71 cubic inches)' '1237.0 ccm (75.48 cubic inches)'
 '197.0 ccm (12.02 cubic inches)' '598.0 ccm (36.49 cubic inches)'
 '497.0 ccm (30.33 cubic inches)' '151.0 ccm (9.21 cubic inches)'
 '49.5 ccm (3.02 cubic inches)' '124.1 ccm (7.57 cubic inches)'
 '500.0 ccm (30.51 cubic inches)' '471.0 ccm (28.74 cubic inches)'
 '72.0 ccm (4.39 cubic inches)' '97.1 ccm (5.93 cubic inches)'
 '2575.0 ccm (157.13 cubic inches)' '2025.0 ccm (123.57 cubic inches)'
 '1645.0 ccm (100.38 cubic inches)' '1647.0 ccm (100.50 cubic inches)'
 '350.0 ccm (21.36 cubic inches)' '798.0 ccm (48.69 cubic inches)'
 '853.0 ccm (52.05 cubic inches)' '895.0 ccm (54.61 cubic inches)'
 '449.5 ccm (27.43 cubic inches)' '1170.0 ccm (71.39 cubic inches)'
 '1130.0 ccm (68.95 cubic inches)' '987.0 ccm (60.23 cubic inches)'
 '1171.0 ccm (71.45 cubic inches)' '1157.0 ccm (70.60 cubic inches)'
 '1293.0 ccm (78.90 cubic inches)' '1649.0 ccm (100.62 cubic inches)'
 '1172.0 ccm (71.52 cubic inches)' '979.0 ccm (59.74 cubic inches)'
 '1085.0 ccm (66.21 cubic inches)' '1185.0 ccm (72.31 cubic inches)'
 '1254.0 ccm (76.52 cubic inches)' '1802.0 ccm (109.96 cubic inches)'
 '594.0 ccm (36.25 cubic inches)' '599.0 ccm (36.55 cubic inches)'
 '848.0 ccm (51.74 cubic inches)' '736.0 ccm (44.91 cubic inches)'
 '192.0 ccm (11.72 cubic inches)' '494.0 ccm (30.14 cubic inches)'
 '596.0 ccm (36.37 cubic inches)' '746.0 ccm (45.52 cubic inches)'
 '740.0 ccm (45.15 cubic inches)' '99.7 ccm (6.08 cubic inches)'
 '102.0 ccm (6.22 cubic inches)' '115.5 ccm (7.04 cubic inches)'
 '144.8 ccm (8.84 cubic inches)' '199.5 ccm (12.17 cubic inches)'
 '220.0 ccm (13.42 cubic inches)' '107.0 ccm (6.53 cubic inches)'
 '230.0 ccm (14.03 cubic inches)' '387.0 ccm (23.61 cubic inches)'
 '486.0 ccm (29.66 cubic inches)' '300.0 ccm (18.31 cubic inches)'
 '399.3 ccm (24.37 cubic inches)' '754.0 ccm (46.01 cubic inches)'
 '249.2 ccm (15.21 cubic inches)' '1131.0 ccm (69.01 cubic inches)'
 '898.5 ccm (54.83 cubic inches)' '373.5 ccm (22.79 cubic inches)'
 '499.6 ccm (30.49 cubic inches)' '134.7 ccm (8.22 cubic inches)'
 '599.6 ccm (36.59 cubic inches)' '899.0 ccm (54.86 cubic inches)'
 '898.0 ccm (54.80 cubic inches)' '152.0 ccm (9.28 cubic inches)'
 '352.0 ccm (21.48 cubic inches)' '110.0 ccm (6.71 cubic inches)'
 '149.6 ccm (9.13 cubic inches)' '650.0 ccm (39.66 cubic inches)'
 '177.3 ccm (10.82 cubic inches)' '199.0 ccm (12.14 cubic inches)'
 '349.0 ccm (21.30 cubic inches)' '194.6 ccm (11.87 cubic inches)'
 '249.7 ccm (15.24 cubic inches)' '249.6 ccm (15.23 cubic inches)'
 '296.5 ccm (18.09 cubic inches)' '296.4 ccm (18.09 cubic inches)'
 '297.3 ccm (18.14 cubic inches)' '79.6 ccm (4.86 cubic inches)'
 '195.0 ccm (11.90 cubic inches)' '274.5 ccm (16.75 cubic inches)'
 '124.7 ccm (7.61 cubic inches)' '398.0 ccm (24.29 cubic inches)'
 '448.0 ccm (27.34 cubic inches)' '349.1 ccm (21.30 cubic inches)'
 '385.4 ccm (23.52 cubic inches)' '430.9 ccm (26.29 cubic inches)'
 '477.5 ccm (29.14 cubic inches)' '510.0 ccm (31.12 cubic inches)'
 '293.1 ccm (17.88 cubic inches)' '1638.8 ccm (100.00 cubic inches)'
 '1868.2 ccm (114.00 cubic inches)' '1819.1 ccm (111.00 cubic inches)'
 '1916.0 ccm (116.91 cubic inches)' '1917.4 ccm (117.00 cubic inches)'
 '1917.0 ccm (116.98 cubic inches)' '1976.0 ccm (120.58 cubic inches)'
 '1198.0 ccm (73.10 cubic inches)' '1198.4 ccm (73.13 cubic inches)'
 '1079.0 ccm (65.84 cubic inches)' '1098.0 ccm (67.00 cubic inches)'
 '1043.0 ccm (63.64 cubic inches)' '996.0 ccm (60.78 cubic inches)'
 '803.0 ccm (49.00 cubic inches)' '1783.0 ccm (108.80 cubic inches)'
 '487.0 ccm (29.72 cubic inches)' '63.6 ccm (3.88 cubic inches)'
 '1125.9 ccm (68.70 cubic inches)' '492.0 ccm (30.02 cubic inches)'
 '491.6 ccm (30.00 cubic inches)' '1203.0 ccm (73.41 cubic inches)'
 '1202.9 ccm (73.40 cubic inches)' '984.0 ccm (60.04 cubic inches)'
 '1199.0 ccm (73.16 cubic inches)' '983.3 ccm (60.00 cubic inches)'
 '644.0 ccm (39.30 cubic inches)' '149.5 ccm (9.12 cubic inches)'
 '292.0 ccm (17.82 cubic inches)' '292.4 ccm (17.84 cubic inches)'
 '400.0 ccm (24.41 cubic inches)' '400.4 ccm (24.43 cubic inches)'
 '649.3 ccm (39.62 cubic inches)' '649.0 ccm (39.60 cubic inches)'
 '693.0 ccm (42.29 cubic inches)' '799.0 ccm (48.75 cubic inches)'
 '495.0 ccm (30.20 cubic inches)' '580.0 ccm (35.39 cubic inches)'
 '800.0 ccm (48.82 cubic inches)' '152.7 ccm (9.32 cubic inches)'
 '149.4 ccm (9.12 cubic inches)' '720.0 ccm (43.93 cubic inches)'
 '450.3 ccm (27.48 cubic inches)' '378.0 ccm (23.07 cubic inches)'
 '123.2 ccm (7.52 cubic inches)' '125.6 ccm (7.67 cubic inches)'
 '645.0 ccm (39.36 cubic inches)' '229.5 ccm (14.00 cubic inches)'
 '249.4 ccm (15.22 cubic inches)' '449.3 ccm (27.42 cubic inches)'
 '69.0 ccm (4.21 cubic inches)' '89.5 ccm (5.46 cubic inches)'
 '976.0 ccm (59.56 cubic inches)' '649.6 ccm (39.64 cubic inches)'
 '799.6 ccm (48.79 cubic inches)' '799.9 ccm (48.81 cubic inches)'
 '1330.0 ccm (81.16 cubic inches)' '750.0 ccm (45.77 cubic inches)'
 '496.2 ccm (30.28 cubic inches)' '450.0 ccm (27.46 cubic inches)'
 '397.0 ccm (24.22 cubic inches)' '229.0 ccm (13.97 cubic inches)'
 '65.0 ccm (3.97 cubic inches)' '1966.0 ccm (119.97 cubic inches)'
 '2146.8 ccm (131.00 cubic inches)' '2163.0 ccm (131.99 cubic inches)'
 '1686.0 ccm (102.88 cubic inches)' '49.8 ccm (3.04 cubic inches)'
 '172.0 ccm (10.50 cubic inches)' '493.9 ccm (30.14 cubic inches)'
 '246.9 ccm (15.07 cubic inches)' '49.6 ccm (3.03 cubic inches)'
 '197.8 ccm (12.07 cubic inches)' '147.5 ccm (9.00 cubic inches)'
 '199.1 ccm (12.15 cubic inches)' '263.7 ccm (16.09 cubic inches)'
 '250.2 ccm (15.27 cubic inches)' '154.4 ccm (9.42 cubic inches)'
 '97.2 ccm (5.93 cubic inches)' '124.8 ccm (7.61 cubic inches)'
 '123.7 ccm (7.55 cubic inches)' '291.0 ccm (17.76 cubic inches)'
 '1285.0 ccm (78.41 cubic inches)' '618.0 ccm (37.71 cubic inches)'
 '748.0 ccm (45.64 cubic inches)' '802.0 ccm (48.94 cubic inches)'
 '849.4 ccm (51.83 cubic inches)' '888.0 ccm (54.19 cubic inches)'
 '904.0 ccm (55.16 cubic inches)' '959.0 ccm (58.52 cubic inches)'
 '955.0 ccm (58.27 cubic inches)' '937.0 ccm (57.18 cubic inches)'
 '989.0 ccm (60.35 cubic inches)' '1262.0 ccm (77.01 cubic inches)'
 '992.0 ccm (60.53 cubic inches)' '821.1 ccm (50.10 cubic inches)'
 '939.0 ccm (57.30 cubic inches)' '583.0 ccm (35.57 cubic inches)'
 '696.0 ccm (42.47 cubic inches)' '821.0 ccm (50.10 cubic inches)'
 '916.0 ccm (55.89 cubic inches)' '1158.0 ccm (70.66 cubic inches)'
 '1103.0 ccm (67.31 cubic inches)' '944.0 ccm (57.60 cubic inches)'
 '849.0 ccm (51.81 cubic inches)' '173.0 ccm (10.56 cubic inches)'
 '88.4 ccm (5.39 cubic inches)' '2100.0 ccm (128.14 cubic inches)'
 '499.0 ccm (30.45 cubic inches)' '349.3 ccm (21.31 cubic inches)'
 '535.0 ccm (32.65 cubic inches)' '648.0 ccm (39.54 cubic inches)'
 '411.0 ccm (25.08 cubic inches)' '700.0 ccm (42.71 cubic inches)'
 '1190.0 ccm (72.61 cubic inches)' '2442.0 ccm (149.01 cubic inches)'
 '124.5 ccm (7.59 cubic inches)' '48.9 ccm (2.98 cubic inches)'
 '183.0 ccm (11.17 cubic inches)' '249.3 ccm (15.21 cubic inches)'
 '294.7 ccm (17.98 cubic inches)' '1064.0 ccm (64.93 cubic inches)'
 '175.8 ccm (10.73 cubic inches)' '272.2 ccm (16.61 cubic inches)'
 '294.1 ccm (17.95 cubic inches)' '247.7 ccm (15.11 cubic inches)'
 '199.4 ccm (12.17 cubic inches)' '249.9 ccm (15.25 cubic inches)'
 '299.3 ccm (18.26 cubic inches)' '293.2 ccm (17.89 cubic inches)'
 '297.0 ccm (18.12 cubic inches)' '290.0 ccm (17.70 cubic inches)'
 '349.7 ccm (21.34 cubic inches)' '515.0 ccm (31.43 cubic inches)'
 '49.9 ccm (3.05 cubic inches)' '449.9 ccm (27.45 cubic inches)'
 '64.9 ccm (3.96 cubic inches)' '84.9 ccm (5.18 cubic inches)'
 '123.3 ccm (7.52 cubic inches)' '179.2 ccm (10.93 cubic inches)'
 '294.0 ccm (17.94 cubic inches)' '72.5 ccm (4.42 cubic inches)'
 '72.5 ccm (4.43 cubic inches)' '272.0 ccm (16.60 cubic inches)'
 '79.1 ccm (4.83 cubic inches)' '113.3 ccm (6.91 cubic inches)'
 '39.9 ccm (2.43 cubic inches)' '98.2 ccm (5.99 cubic inches)'
 '106.7 ccm (6.51 cubic inches)' '1151.0 ccm (70.23 cubic inches)'
 '193.2 ccm (11.79 cubic inches)' '97.0 ccm (5.92 cubic inches)'
 '492.7 ccm (30.06 cubic inches)' '498.8 ccm (30.43 cubic inches)'
 '448.8 ccm (27.39 cubic inches)' '280.0 ccm (17.09 cubic inches)'
 '360.0 ccm (21.97 cubic inches)' '182.7 ccm (11.15 cubic inches)'
 '249.1 ccm (15.20 cubic inches)' '182.6 ccm (11.14 cubic inches)'
 '1868.0 ccm (113.99 cubic inches)' '1923.0 ccm (117.34 cubic inches)'
 '1753.5 ccm (107.00 cubic inches)' '1202.0 ccm (73.35 cubic inches)'
 '1745.0 ccm (106.48 cubic inches)' '1201.3 ccm (73.30 cubic inches)'
 '1338.0 ccm (81.64 cubic inches)' '1337.0 ccm (81.58 cubic inches)'
 '883.3 ccm (53.90 cubic inches)' '1802.7 ccm (110.00 cubic inches)'
 '1801.0 ccm (109.90 cubic inches)' '1688.0 ccm (103.00 cubic inches)'
 '1746.0 ccm (106.54 cubic inches)' '1690.0 ccm (103.12 cubic inches)'
 '1450.0 ccm (88.48 cubic inches)' '1689.6 ccm (103.10 cubic inches)'
 '1573.3 ccm (96.00 cubic inches)' '1449.0 ccm (88.42 cubic inches)'
 '999.7 ccm (61.00 cubic inches)' '1000.0 ccm (61.02 cubic inches)'
 '1212.7 ccm (74.00 cubic inches)' '1208.0 ccm (73.71 cubic inches)'
 '1212.0 ccm (73.96 cubic inches)' '1573.0 ccm (95.98 cubic inches)'
 '1584.0 ccm (96.66 cubic inches)' '1499.0 ccm (91.47 cubic inches)'
 '1442.2 ccm (88.00 cubic inches)' '1800.0 ccm (109.84 cubic inches)'
 '1803.0 ccm (110.02 cubic inches)' '1338.6 ccm (81.68 cubic inches)'
 '1747.0 ccm (106.60 cubic inches)' '883.0 ccm (53.88 cubic inches)'
 '743.0 ccm (45.34 cubic inches)' '1247.0 ccm (76.09 cubic inches)'
 '1250.4 ccm (76.30 cubic inches)' '213.0 ccm (13.00 cubic inches)'
 '1200.0 ccm (73.22 cubic inches)' '1252.1 ccm (76.40 cubic inches)'
 '753.9 ccm (46.00 cubic inches)' '1250.1 ccm (76.28 cubic inches)'
 '1130.8 ccm (69.00 cubic inches)' '1250.0 ccm (76.28 cubic inches)'
 '1179.9 ccm (72.00 cubic inches)' '1199.6 ccm (73.20 cubic inches)'
 '882.7 ccm (53.86 cubic inches)' '223.0 ccm (13.61 cubic inches)'
 '191.0 ccm (11.65 cubic inches)' '149.2 ccm (9.10 cubic inches)'
 '97.5 ccm (5.95 cubic inches)' '109.0 ccm (6.65 cubic inches)'
 '110.9 ccm (6.77 cubic inches)' '109.2 ccm (6.66 cubic inches)'
 '113.0 ccm (6.90 cubic inches)' '109.1 ccm (6.66 cubic inches)'
 '113.2 ccm (6.91 cubic inches)' '199.6 ccm (12.18 cubic inches)'
 '936.0 ccm (57.11 cubic inches)' '950.0 ccm (57.97 cubic inches)'
 '98.0 ccm (5.98 cubic inches)' '745.0 ccm (45.46 cubic inches)'
 '919.0 ccm (56.08 cubic inches)' '330.0 ccm (20.14 cubic inches)'
 '184.0 ccm (11.23 cubic inches)' '1084.0 ccm (66.15 cubic inches)'
 '108.0 ccm (6.59 cubic inches)' '675.0 ccm (41.19 cubic inches)'
 '89.0 ccm (5.43 cubic inches)' '1140.0 ccm (69.56 cubic inches)'
 '325.0 ccm (19.83 cubic inches)' '447.0 ccm (27.28 cubic inches)'
 '572.0 ccm (34.90 cubic inches)' '655.0 ccm (39.97 cubic inches)'
 '747.0 ccm (45.58 cubic inches)' '149.1 ccm (9.10 cubic inches)'
 '162.7 ccm (9.93 cubic inches)' '123.9 ccm (7.56 cubic inches)'
 '1284.0 ccm (78.35 cubic inches)' '286.0 ccm (17.45 cubic inches)'
 '348.3 ccm (21.25 cubic inches)' '305.0 ccm (18.61 cubic inches)'
 '599.9 ccm (36.61 cubic inches)' '599.3 ccm (36.57 cubic inches)'
 '1137.0 ccm (69.38 cubic inches)' '929.0 ccm (56.69 cubic inches)'
 '84.7 ccm (5.17 cubic inches)' '156.8 ccm (9.57 cubic inches)'
 '80.0 ccm (4.88 cubic inches)' '149.7 ccm (9.13 cubic inches)'
 '295.5 ccm (18.03 cubic inches)' '413.0 ccm (25.20 cubic inches)'
 '449.7 ccm (27.44 cubic inches)' '670.0 ccm (40.88 cubic inches)'
 '1261.0 ccm (76.95 cubic inches)' '496.0 ccm (30.27 cubic inches)'
 '673.0 ccm (41.07 cubic inches)' '782.0 ccm (47.72 cubic inches)'
 '680.0 ccm (41.49 cubic inches)' '680.2 ccm (41.51 cubic inches)'
 '109.5 ccm (6.68 cubic inches)' '1298.0 ccm (79.20 cubic inches)'
 '582.0 ccm (35.51 cubic inches)' '999.8 ccm (61.01 cubic inches)'
 '279.0 ccm (17.02 cubic inches)' '329.6 ccm (20.11 cubic inches)'
 '475.0 ccm (28.98 cubic inches)' '518.0 ccm (31.61 cubic inches)'
 '420.0 ccm (25.63 cubic inches)' '1312.0 ccm (80.06 cubic inches)'
 '1181.0 ccm (72.06 cubic inches)' '1520.0 ccm (92.75 cubic inches)'
 '1832.0 ccm (111.79 cubic inches)' '1833.0 ccm (111.85 cubic inches)'
 '781.0 ccm (47.66 cubic inches)' '258.9 ccm (15.80 cubic inches)'
 '288.0 ccm (17.57 cubic inches)' '298.0 ccm (18.18 cubic inches)'
 '259.0 ccm (15.80 cubic inches)' '153.0 ccm (9.34 cubic inches)'
 '157.0 ccm (9.58 cubic inches)' '1300.0 ccm (79.33 cubic inches)'
 '279.1 ccm (17.03 cubic inches)' '329.2 ccm (20.09 cubic inches)'
 '582.2 ccm (35.53 cubic inches)' '155.3 ccm (9.48 cubic inches)'
 '282.0 ccm (17.21 cubic inches)' '679.0 ccm (41.43 cubic inches)'
 '86.0 ccm (5.25 cubic inches)' '699.0 ccm (42.65 cubic inches)'
 '491.0 ccm (29.96 cubic inches)' '694.5 ccm (42.38 cubic inches)'
 '749.5 ccm (45.73 cubic inches)' '1795.0 ccm (109.53 cubic inches)'
 '196.9 ccm (12.01 cubic inches)' '1218.0 ccm (74.32 cubic inches)'
 '449.3 ccm (27.41 cubic inches)' '549.8 ccm (33.55 cubic inches)'
 '555.0 ccm (33.87 cubic inches)' '248.6 ccm (15.17 cubic inches)'
 '393.3 ccm (24.00 cubic inches)' '510.4 ccm (31.14 cubic inches)'
 '565.5 ccm (34.51 cubic inches)' '595.0 ccm (36.31 cubic inches)'
 '628.3 ccm (38.34 cubic inches)' '293.0 ccm (17.88 cubic inches)'
 '692.7 ccm (42.27 cubic inches)' '249.5 ccm (15.22 cubic inches)'
 '510.9 ccm (31.18 cubic inches)' '399.5 ccm (24.38 cubic inches)'
 '576.3 ccm (35.17 cubic inches)' '576.3 ccm (35.16 cubic inches)'
 '610.0 ccm (37.22 cubic inches)' '633.6 ccm (38.66 cubic inches)'
 '449.6 ccm (27.43 cubic inches)' '478.0 ccm (29.17 cubic inches)'
 '375.0 ccm (22.88 cubic inches)' '373.0 ccm (22.76 cubic inches)'
 '500.8 ccm (30.56 cubic inches)' '144.0 ccm (8.79 cubic inches)'
 '577.0 ccm (35.21 cubic inches)' '302.4 ccm (18.45 cubic inches)'
 '348.8 ccm (21.28 cubic inches)' '296.0 ccm (18.06 cubic inches)'
 '678.2 ccm (41.38 cubic inches)' '276.0 ccm (16.84 cubic inches)'
 '1769.9 ccm (108.00 cubic inches)' '1768.0 ccm (107.88 cubic inches)'
 '1442.0 ccm (87.99 cubic inches)' '1811.0 ccm (110.51 cubic inches)'
 '1890.0 ccm (115.33 cubic inches)' '1638.0 ccm (99.95 cubic inches)'
 '1901.0 ccm (116.00 cubic inches)' '1133.0 ccm (69.14 cubic inches)'
 '200.0 ccm (12.20 cubic inches)' '168.9 ccm (10.31 cubic inches)'
 '145.0 ccm (8.85 cubic inches)' '225.0 ccm (13.73 cubic inches)'
 '343.5 ccm (20.96 cubic inches)' '651.9 ccm (39.78 cubic inches)'
 '147.0 ccm (8.97 cubic inches)' '233.8 ccm (14.27 cubic inches)'
 '1050.0 ccm (64.07 cubic inches)' '1148.0 ccm (70.05 cubic inches)'
 '1195.0 ccm (72.92 cubic inches)' '1301.0 ccm (79.39 cubic inches)'
 '143.7 ccm (8.77 cubic inches)' '143.6 ccm (8.76 cubic inches)'
 '193.0 ccm (11.78 cubic inches)' '248.8 ccm (15.18 cubic inches)'
 '373.2 ccm (22.77 cubic inches)' '393.4 ccm (24.01 cubic inches)'
 '447.9 ccm (27.33 cubic inches)' '449.4 ccm (27.42 cubic inches)'
 '477.0 ccm (29.11 cubic inches)' '609.0 ccm (37.16 cubic inches)'
 '625.0 ccm (38.14 cubic inches)' '654.0 ccm (39.91 cubic inches)'
 '690.0 ccm (42.10 cubic inches)' '653.7 ccm (39.89 cubic inches)'
 '889.0 ccm (54.25 cubic inches)' '942.0 ccm (57.48 cubic inches)'
 '1352.0 ccm (82.50 cubic inches)' '228.0 ccm (13.91 cubic inches)'
 '271.0 ccm (16.54 cubic inches)' '633.0 ccm (38.63 cubic inches)'
 '252.0 ccm (15.38 cubic inches)' '299.0 ccm (18.24 cubic inches)'
 '216.0 ccm (13.18 cubic inches)' '697.0 ccm (42.53 cubic inches)'
 '651.0 ccm (39.72 cubic inches)' '111.0 ccm (6.77 cubic inches)'
 '112.0 ccm (6.83 cubic inches)' '64.7 ccm (3.95 cubic inches)'
 '64.0 ccm (3.91 cubic inches)' '84.0 ccm (5.13 cubic inches)'
 '84.6 ccm (5.16 cubic inches)' '694.0 ccm (42.35 cubic inches)'
 '1441.0 ccm (87.93 cubic inches)' '636.0 ccm (38.81 cubic inches)'
 '362.0 ccm (22.09 cubic inches)' '1471.0 ccm (89.76 cubic inches)'

In [29]:
for i in bike_cleaned_df["Fuel capacity"]:
    print(i.split()[0])
    print()

7.50

7.50

7.50

7.00

7.50

7.50

7.50

7.00

7.00

7.00

7.00

7.50

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.50

7.00

7.50

7.50

7.50

7.50

7.00

7.00

7.00

7.50

7.50

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.50

7.50

7.50

7.50

7.50

7.50

7.00

7.00

7.50

7.50

17.00

17.00

17.00

17.00

17.00

8.00

8.00

9.50

9.50

9.50

9.50

10.00

13.50

4.70

8.00

8.00

8.00

18.00

11.20

11.20

11.20

11.20

11.20

5.00

14.00

14.00

14.00

6.00

13.50

13.50

13.50

5.50

5.50

5.50

10.00

14.00

14.00

4.70

4.70

4.70

4.70

4.70

4.70

6.30

19.00

13.00

8.50

8.50

8.50

8.50

12.50

12.50

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

13.50

13.50

13.50

13.50

13.50

13.50

13.50

13.50

13.50

13.50

13.50

13.50

13.50

13.50

13.50

16.00

13.50

13.50

13.50

13.50

13.50

13.50

13.50

13.50

16.00

16.00

16.00

16.00

4.50

6.70

4.60

4.60

4.50

4.50

18.00

18.00

18.00

18.00

18.50

18.50

6.00

6.00

6.00

8.00

14.00

14.00

14.00

14.00

14.00

14.00

28.00

6.00

8.00

7.57

18.00

18.00

16.00

16.00

16.00

16.00

16.00

16.00

17.41

14.00

14.00

14.00

14.00

17.03

17.03

17.03

17.03

14.00

14.00

14.00

15.90

15.90

15.90

13.50

13.50

12.00

12.00

12.00

7.00

7.00

12.00

15.00

15.00

15.00

6.00

6.20

6.20

4.75

13.50

13.50

13.50

5.50

8.00

7.30

7.30

7.30

7.30

9.30

5.00

5.00

9.30

9.30

14.00

14.00

23.00

14.00

14.00

7.00

13.50

13.50

13.50

13.50

13.50

13.50

3.40

3.40

6.00

6.00

7.00

7.00

8.00

24.00

13.00

5.00

5.00

13.50

13.50

13.50

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

14.00

6.50

6.50

6.50

6.50

9.50

9.50

9.50

9.50

9.50

40.00

10.50

8.50

15.00

14.00

15.00

24.00

24.00

24.00

24.00

24.00

24.00

24.00

24.00

24.00

24.00

24.00

24.00

24.00

24.00

25.00

25.00

25.00

13.00

10.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

25.00

25.00

25.00

18.00

18.00

11.00

9.50

7.40

7.40

7.40

7.40

7.40

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

2.80

7.70

14.00

19.50

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

21.00

25.00

21.00

21.00

25.00

14.00

14.00

14.00

14.00

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.00

14.00

14.50

14.50

12.20

13.00

13.00

13.00

14.50

13.00

14.50

14.50

14.50

13.00

13.00

13.00

15.00

15.00

15.00

15.00

15.00

22.00

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

14.50

21.00

21.00

18.00

19.00

18.00

15.00

22.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.50

18.50

18.50

18.50

18.50

17.00

17.00

17.00

17.00

17.00

17.00

18.50

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

18.50

17.00

17.00

17.00

17.00

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

10.00

10.00

7.50

7.50

7.50

7.50

7.00

9.50

9.50

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

14.50

7.00

7.00

7.00

7.00

9.50

9.50

9.50

7.80

21.00

18.00

15.00

6.00

6.00

6.00

7.00

7.60

6.50

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

6.50

7.00

9.00

9.00

15.50

15.50

15.50

15.50

15.50

15.50

15.50

15.00

15.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

18.50

18.50

18.50

18.50

18.50

18.80

18.80

18.80

18.50

18.50

18.50

18.00

18.00

10.00

10.00

10.00

10.00

10.00

7.50

7.50

10.00

10.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.80

7.80

7.80

8.40

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

9.50

9.50

6.00

8.00

8.00

8.00

8.00

8.00

9.50

13.20

13.20

11.00

10.00

10.00

13.20

13.50

8.00

7.50

7.50

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.50

7.50

12.20

7.00

8.00

8.00

7.50

8.00

7.50

8.00

8.00

8.00

7.50

7.50

7.50

7.50

7.50

7.50

17.00

17.00

13.20

13.50

13.50

13.50

13.50

16.00

16.00

16.00

15.00

15.00

15.00

15.00

15.00

16.00

15.00

15.00

15.00

15.00

15.00

15.00

16.00

16.00

16.00

16.00

16.00

16.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

8.00

8.00

8.00

9.00

7.50

9.00

8.97

7.50

9.00

9.00

9.00

9.00

7.00

7.00

7.00

9.30

9.00

9.30

9.00

10.50

6.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

19.00

14.00

14.00

14.00

14.50

14.50

14.50

13.00

15.00

15.00

18.00

18.50

17.90

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

18.50

17.90

17.00

17.00

18.50

17.00

17.00

17.00

17.00

20.10

21.57

21.57

21.57

20.10

8.71

8.71

8.71

12.50

16.30

16.30

16.30

16.30

21.57

21.57

21.57

21.57

21.00

21.50

21.50

21.57

21.57

21.57

21.60

21.57

21.57

21.57

21.57

21.57

21.57

21.60

21.57

21.57

21.60

21.57

21.57

24.60

21.57

24.60

21.57

21.57

21.57

21.60

21.57

5.68

5.70

5.68

12.49

16.30

12.11

16.28

16.30

16.00

16.00

22.71

22.70

22.70

22.70

21.60

22.70

5.68

5.70

5.30

20.10

20.06

20.06

20.10

20.10

20.06

5.68

5.68

20.06

20.10

21.60

21.60

20.10

20.06

20.06

20.06

21.60

21.57

21.57

21.60

21.60

20.06

21.57

20.06

21.95

21.95

21.95

22.00

22.00

22.00

20.10

20.10

20.06

20.06

20.06

20.10

20.00

20.81

20.06

20.00

21.57

21.50

21.50

20.06

20.06

20.10

20.80

20.81

20.10

20.10

20.81

20.06

20.06

20.06

20.80

20.06

20.06

20.10

20.10

20.81

21.57

21.57

21.57

20.81

20.10

20.06

20.06

21.57

20.06

20.06

20.06

16.28

16.28

16.28

22.71

20.06

20.00

20.00

20.00

20.00

20.00

13.50

14.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

13.25

13.25

13.25

13.25

13.25

13.25

23.00

23.00

23.00

23.00

23.00

23.00

23.00

23.00

23.00

23.00

23.00

23.00

23.00

23.00

23.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

18.93

18.93

18.93

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

9.00

13.60

11.36

15.14

15.14

15.14

15.00

9.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

11.00

11.00

11.00

11.00

11.00

11.00

9.00

9.00

9.00

9.00

9.00

9.00

9.00

9.00

11.00

11.00

11.00

11.00

11.00

11.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

17.03

15.90

15.90

15.90

15.90

15.90

15.90

15.90

15.90

15.90

15.90

15.90

15.90

14.80

14.80

14.80

14.80

14.80

14.80

14.80

14.80

14.80

13.25

13.25

13.25

13.25

13.25

13.25

13.25

13.25

13.25

13.25

13.25

13.25

16.00

16.00

16.00

16.00

17.03

17.03

13.25

13.25

11.90

11.90

11.90

12.00

6.70

5.50

5.50

5.50

5.50

5.50

5.50

12.30

12.30

15.52

15.52

9.00

9.00

9.00

8.50

8.60

9.00

8.60

9.20

9.20

9.25

9.20

12.00

9.20

9.20

9.20

12.00

12.00

9.00

9.70

22.00

22.00

22.00

21.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

12.80

12.80

12.80

12.80

12.80

12.80

12.80

15.90

15.90

16.00

16.00

16.00

16.00

16.00

15.50

16.00

15.50

16.00

15.90

15.90

15.90

15.90

15.50

15.90

15.90

17.30

15.00

17.30

17.30

17.30

17.30

16.00

16.00

16.00

16.00

16.00

17.30

17.30

17.30

16.00

15.90

16.00

16.00

16.00

16.00

16.00

16.00

16.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

16.00

16.00

16.00

15.90

16.00

16.00

16.00

16.00

16.00

16.00

24.00

24.00

24.00

24.00

24.00

24.00

24.00

16.00

16.00

16.00

16.00

16.00

16.00

15.14

15.00

15.00

15.00

15.00

15.00

15.00

16.00

16.00

16.00

15.90

16.00

16.00

15.00

15.00

15.00

15.00

16.00

15.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

15.00

15.00

15.00

15.00

15.14

23.00

23.00

23.00

23.00

15.00

15.00

15.00

13.00

13.00

15.50

15.50

17.30

17.30

16.00

16.00

11.00

11.00

11.00

11.50

11.50

11.00

11.00

10.98

8.00

8.00

15.14

15.14

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

9.50

9.50

9.50

9.50

9.50

9.50

9.50

9.50

9.50

13.00

13.00

13.00

13.00

13.00

13.00

13.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

17.41

17.50

17.50

17.50

17.50

17.50

17.50

17.50

22.00

20.50

20.50

24.00

24.00

24.00

24.00

24.00

24.00

24.00

24.00

19.00

19.00

19.00

20.50

20.50

19.00

19.00

24.00

24.00

24.00

19.00

19.00

19.00

19.00

19.00

19.00

19.00

19.00

19.00

19.00

19.00

19.00

19.00

18.93

19.00

19.00

19.00

19.00

19.00

18.93

19.00

19.00

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

24.00

26.50

24.00

24.00

24.00

26.50

26.50

26.50

26.50

26.50

26.50

24.00

24.00

26.50

24.00

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

26.50

24.00

24.00

19.00

19.00

16.50

16.50

35.00

24.00

22.00

25.00

21.00

23.00

23.00

26.00

25.00

18.00

18.00

18.00

18.00

22.10

30.00

20.40

20.50

20.50

20.50

20.50

20.50

20.50

23.00

22.00

25.00

25.20

25.20

17.00

17.50

17.50

17.50

17.50

17.50

17.50

17.50

17.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.06

20.00

20.00

20.00

20.00

20.00

20.00

20.00

33.00

33.00

33.00

33.00

33.00

32.93

30.00

30.00

30.00

30.00

30.00

33.00

30.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

17.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

27.00

16.00

16.00

27.00

25.00

25.00

24.98

25.00

25.00

25.00

25.00

25.00

25.00

25.00

25.00

25.00

17.00

17.00

17.00

21.00

16.00

20.00

20.00

20.00

19.68

19.68

30.00

30.00

30.00

29.90

29.90

30.00

25.00

18.00

15.14

18.17

20.00

18.00

18.00

18.00

25.00

25.00

25.00

16.01

16.01

24.22

16.01

16.01

16.01

23.85

11.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

24.00

17.00

17.00

21.00

20.50

20.50

20.50

18.00

18.00

18.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

18.00

17.00

17.00

17.00

18.00

18.00

18.00

17.00

17.00

17.00

17.00

17.00

17.00

18.00

18.00

18.00

17.00

17.00

17.00

18.00

18.00

17.00

17.00

17.00

17.00

17.00

20.00

33.00

18.00

27.00

17.00

21.00

14.00

14.00

14.00

11.00

11.00

11.00

11.00

11.00

11.00

12.00

12.00

9.60

9.60

9.60

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

12.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

15.00

14.00

14.00

14.00

14.00

12.00

15.00

15.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

24.00

24.00

24.00

24.00

17.00

17.00

17.00

14.00

14.00

14.00

14.00

14.00

17.00

17.00

17.00

17.00

15.00

17.00

17.00

17.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

14.00

14.00

14.00

14.00

17.50

17.50

17.50

17.50

17.50

17.50

17.50

17.50

17.50

17.50

17.50

17.41

17.50

17.50

17.50

17.50

17.50

17.50

16.50

16.50

16.50

17.50

17.50

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

19.00

19.00

19.00

10.50

10.50

10.50

10.50

10.50

11.00

10.00

11.50

11.00

11.00

11.00

11.00

15.00

12.00

15.00

15.00

10.00

4.00

4.00

4.00

4.00

4.00

4.00

4.00

5.00

5.00

18.93

8.60

8.60

5.00

6.50

12.00

9.00

13.50

8.80

4.00

4.00

15.14

4.00

4.00

4.00

4.00

4.00

10.00

6.30

6.30

6.30

6.30

6.30

6.80

6.80

5.50

5.50

5.50

5.50

4.80

16.00

16.00

6.20

6.20

21.00

21.00

21.00

21.00

14.50

14.50

14.50

14.50

13.50

13.50

13.50

13.50

16.50

17.00

17.00

17.00

17.00

17.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

14.00

27.00

27.00

27.00

27.00

15.00

15.00

15.00

15.00

15.00

9.60

17.00

17.00

7.40

7.40

7.40

7.40

7.40

7.40

7.40

7.40

7.50

11.50

10.60

17.00

16.00

16.00

12.00

12.00

12.00

12.00

15.00

13.50

13.50

12.50

14.00

14.00

14.00

12.50

15.00

13.50

13.50

12.70

12.70

15.00

12.70

15.00

12.70

15.00

13.50

15.00

7.40

7.40

7.40

11.00

11.00

7.40

7.50

7.50

7.50

6.00

7.50

7.50

7.50

6.20

6.20

6.00

6.00

6.00

17.00

17.00

16.00

16.00

16.00

17.00

17.00

22.00

7.20

7.20

7.20

17.00

15.97

15.97

16.00

14.99

14.99

15.00

27.00

16.00

16.00

16.00

16.00

16.00

17.00

16.00

16.00

22.00

21.50

17.00

17.00

17.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

20.00

17.00

7.20

14.00

7.20

7.20

7.20

7.20

7.20

7.20

15.00

17.00

17.00

17.00

17.00

17.00

16.00

16.00

7.20

19.00

19.00

19.00

9.00

22.00

22.00

22.00

22.00

22.00

22.00

22.00

22.00

22.00

22.00

22.00

11.70

6.20

10.70

13.50

13.50

13.50

14.38

14.38

16.28

16.28

16.28

16.28

16.28

16.28

14.38

14.38

14.38

14.38

16.28

16.28

16.28

16.28

16.28

2.20

1.89

1.89

1.89

11.36

22.71

22.71

21.95

15.14

9.46

6.80

6.80

7.50

7.50

7.50

7.50

7.50

7.50

6.80

6.80

7.00

6.80

6.80

6.00

10.50

10.50

10.50

7.50

7.50

7.50

7.50

7.50

7.50

7.50

7.50

7.50

22.00

2.80

2.80

2.60

2.80

2.80

2.60

2.80

2.80

2.80

2.80

2.80

2.80

2.80

2.60

2.60

2.50

2.50

2.80

2.80

2.80

2.80

2.80

2.60

19.00

10.50

10.50

2.00

2.00

2.00

2.00

10.50

5.70

3.20

3.20

3.20

3.20

2.50

7.30

7.30

7.30

9.50

6.00

6.00

8.50

9.50

9.50

8.50

8.50

8.50

9.00

9.00

9.00

9.00

8.50

9.00

9.00

9.00

9.00

8.50

8.50

9.00

9.00

9.00

8.50

7.00

6.00

6.00

6.00

6.00

7.00

6.00

6.00

6.50

6.50

6.50

8.50

9.50

9.50

5.70

6.00

6.00

6.00

6.00

6.50

6.50

6.50

7.50

6.00

6.00

6.00

9.50

9.50

9.50

6.00

6.00

6.00

8.50

8.50

8.50

8.50

19.30

19.30

19.30

19.30

19.30

12.86

12.30

12.86

12.86

12.30

12.86

15.14

15.14

12.30

12.30

15.14

15.14

14.66

17.78

16.65

16.60

16.60

17.00

17.00

17.00

18.00

18.00

14.00

13.50

13.50

13.50

14.00

14.00

13.50

18.00

18.00

18.00

18.00

18.00

17.98

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

18.00

18.00

16.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

18.00

14.00

14.00

14.00

13.50

13.50

13.50

21.00

19.00

18.00

19.00

19.00

21.00

16.00

16.00

18.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

16.00

17.00

17.00

16.00

16.00

5.50

9.00

9.00

9.00

9.00

37.00

37.00

9.50

8.50

8.50

8.50

8.50

8.00

8.00

24.00

17.00

17.00

3.00

3.50

3.50

3.50

3.50

3.00

3.00

20.06

20.06

20.06

20.00

10.60

10.60

10.60

10.59

10.60

10.59

14.00

14.00

14.45

14.45

14.00

14.00

14.00

13.00

16.65

14.00

13.00

14.00

14.45

14.45

14.00

14.00

14.45

19.00

18.90

18.92

20.40

20.40

16.65

16.65

16.65

17.00

17.00

15.80

15.80

14.45

14.45

14.45

16.65

16.65

16.65

16.60

14.00

14.45

14.45

12.00

13.00

14.00

14.00

14.00

14.00

14.00

14.00

17.00

17.00

20.00

20.00

20.00

14.00

14.00

14.00

12.00

14.00

14.00

12.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

10.00

10.00

10.00

12.50

12.50

12.50

12.50

12.50

12.00

12.00

19.00

17.00

17.00

17.00

19.00

19.50

18.00

18.00

18.00

18.00

17.00

17.00

17.00

17.00

17.00

17.00

17.50

17.50

22.00

13.00

13.00

13.00

19.00

19.00

15.00

15.00

14.00

15.00

14.00

15.00

14.00

19.00

15.00

15.00

14.00

14.00

18.50

19.00

18.00

18.00

18.00

25.00

23.00

23.00

26.00

16.50

8.00

8.00

7.50

16.50

16.50

16.50

9.00

9.00

8.30

5.20

5.20

7.00

7.00

7.20

7.00

3.60

3.60

15.00

15.50

15.50

15.50

15.50

15.50

15.50

15.50

15.50

15.50

12.50

12.50

12.50

12.50

12.50

14.00

12.50

12.50

12.50

12.50

12.50

12.50

12.00

14.00

14.00

12.50

12.50

20.06

19.00

11.50

8.00

14.00

14.00

14.00

14.00

14.00

14.00

20.06

15.20

12.50

12.50

12.50

12.50

19.30

15.20

19.30

15.20

15.90

19.98

19.98

18.93

15.90

15.90

15.90

19.98

19.98

15.14

15.14

10.98

10.98

10.98

10.98

12.50

12.49

11.35

11.35

11.36

11.36

6.06

6.06

6.05

6.06

2.70

2.70

20.50

20.44

16.28

16.30

16.30

16.30

20.44

20.44

20.44

20.44

20.44

20.44

20.44

20.44

20.50

20.44

20.50

20.50

27.00

27.00

27.00

25.00

25.00

25.00

25.00

27.00

25.00

27.00

27.00

26.98

25.00

25.00

25.00

25.00

25.00

25.00

25.00

25.00

9.00

9.00

9.00

10.00

19.00

19.00

19.00

8.71

8.71

8.71

8.71

8.71

8.70

8.71

8.71

8.71

15.00

15.00

12.00

12.00

3.40

8.00

8.00

15.00

15.00

4.20

2.60

2.60

2.60

2.60

2.80

2.80

2.80

4.20

4.20

4.20

3.02

17.03

14.19

16.25

17.03

17.03

4.20

3.50

12.50

12.50

12.50

12.50

12.50

9.50

9.50

9.50

9.50

15.00

7.10

7.20

7.20

7.10

6.00

5.00

5.00

5.00

5.00

6.00

5.90

5.90

17.00

17.00

16.80

6.50

6.20

8.00

8.00

15.00

16.00

16.00

15.00

15.00

15.00

15.00

15.00

8.00

8.00

5.00

9.50

9.50

9.50

9.60

9.50

9.50

11.50

11.50

11.50

11.50

12.70

12.70

12.70

12.70

16.00

16.00

15.00

15.00

15.00

15.00

15.00

15.00

17.30

5.00

4.50

12.00

5.50

16.00

10.00

10.00

10.00

14.00

17.50

17.50

11.60

11.60

4.00

14.70

14.00

13.00

13.30

6.90

15.00

15.00

10.00

7.00

7.10

7.10

7.10

7.00

7.00

7.00

7.00

7.10

7.00

7.00

7.10

7.10

11.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

2.00

7.00

7.00

2.30

2.30

11.00

11.00

11.00

11.00

11.00

11.00

11.00

11.00

8.00

14.00

14.00

14.00

14.00

14.00

14.00

14.00

13.00

13.00

13.00

7.25

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

11.00

11.00

11.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

13.00

11.00

13.00

13.00

7.50

7.50

7.50

7.50

7.50

7.50

7.50

7.50

7.50

7.00

7.00

7.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

8.00

7.50

7.50

8.00

8.00

8.00

8.00

8.00

7.00

7.00

7.00

7.00

7.00

6.50

6.50

6.50

6.50

6.50

6.50

6.50

6.50

6.50

6.50

6.50

6.50

6.50

6.50

7.00

7.00

7.00

7.00

6.50

7.00

7.00

7.00

7.00

7.00

7.00

7.50

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

5.50

7.00

7.00

7.00

7.00

8.00

7.00

5.50

7.00

15.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

7.00

8.00

7.00

8.00

7.00

7.00

7.00

7.00

7.00

8.00

6.00

6.00

6.00

6.00

6.00

7.00

5.50

7.00

12.00

12.00

11.00

11.00

11.00

11.00

11.00

11.00

11.00

11.00

11.00

7.00

4.00

7.50

7.00

7.00

7.00

7.00

7.00

7.00

20.00

11.50

5.20

18.00

15.50

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

7.20

17.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

16.00

16.00

16.00

16.00

17.00

17.00

17.00

17.00

15.50

15.50

15.50

15.50

15.50

15.50

18.30

18.30

18.30

15.50

15.50

15.50

16.00

16.00

16.00

15.50

15.50

18.00

19.00

17.00

17.00

16.00

17.00

17.00

17.00

17.00

17.00

17.00

17.00

15.50

15.50

15.50

15.50

In [30]:
bike_cleaned_df["Fuel capacity"]=bike_cleaned_df["Fuel capacity"].str.split().str[0]

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\1547727730.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned_df["Fuel capacity"]=bike_cleaned_df["Fuel capacity"].str.split().str[0]

In [31]:
bike_cleaned_df.head()

,Model,Category,Displacement,Engine type,Bore x stroke,Fuel system,Cooling system,Gearbox,Transmission type,Fuel capacity,Front tire,Rear tire,Front brakes,Rear brakes
0,AJP GALP 50 Enduro,Enduro / offroad,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,80/90-21,110/80-18,Single disc,Single disc
1,AJP GALP 50 R,Sport,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,130/80-17,130/70-17,Single disc,Single disc
2,AJP GALP 50 Supermotard,Super motard,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,100/80-17,130/70-17,Single disc,Single disc
5,AJP PR3 125 Supermoto,Super motard,124.0 ccm (7.57 cubic inches),"Single cylinder, four-stroke",56.5 x 49.5 mm (2.2 x 1.9 inches),Carburettor. Walbro 30 mm,Air,5-speed,Chain (final drive),7.00,100/80-17,130/70-17,Single disc,Single disc. 2-piston caliper
6,AJP PR3 240 Enduro,Enduro / offroad,233.0 ccm (14.22 cubic inches),"Single cylinder, four-stroke",69.0 x 62.5 mm (2.7 x 2.5 inches),Carburettor. Walbro 30 mm,Oil & air,5-speed,Chain (final drive),7.50,70/100-19,100/100-17,Single disc. 2-piston calipers,Single disc

In [32]:
print(bike_cleaned_df["Displacement"].nunique())
bike_cleaned_df["Displacement"].value_counts()

851

Displacement
249.0 ccm (15.19 cubic inches)     548
124.0 ccm (7.57 cubic inches)      457
125.0 ccm (7.63 cubic inches)      444
49.0 ccm (2.99 cubic inches)       415
998.0 ccm (60.90 cubic inches)     321
                                  ...
1401.0 ccm (85.49 cubic inches)      1
998.6 ccm (60.93 cubic inches)       1
84.6 ccm (5.16 cubic inches)         1
64.0 ccm (3.91 cubic inches)         1
643.0 ccm (39.24 cubic inches)       1
Name: count, Length: 851, dtype: int64

In [33]:
print(bike_cleaned_df["Engine type"].nunique())
print()
bike_cleaned_df["Engine type"].value_counts()

21

Engine type
Single cylinder, four-stroke        6238
V2, four-stroke                     3679
Single cylinder, two-stroke         1822
In-line four, four-stroke           1447
Twin, four-stroke                   1388
In-line three, four-stroke           534
Two cylinder boxer, four-stroke      311
V4, four-stroke                      263
Six cylinder boxer, four-stroke      110
In-line six, four-stroke              51
Two cylinder boxer, two-stroke        43
Twin, two-stroke                      42
V6, four-stroke                       39
Square four cylinder                  32
Diesel                                19
Four cylinder boxer, four-stroke      11
V8, four-stroke                        3
V4, two-stroke                         2
V2, two-stroke                         2
In-line three, two-stroke              2
In-line four, two-stroke               2
Name: count, dtype: int64

In [34]:
bike_cleaned_df["Bore x stroke"].value_counts().head(10)

Bore x stroke
40.0 x 39.2 mm (1.6 x 1.5 inches)     228
52.4 x 57.8 mm (2.1 x 2.3 inches)     222
77.0 x 53.6 mm (3.0 x 2.1 inches)     215
40.3 x 39.0 mm (1.6 x 1.5 inches)     204
54.0 x 54.0 mm (2.1 x 2.1 inches)     192
54.0 x 54.5 mm (2.1 x 2.1 inches)     187
76.0 x 55.0 mm (3.0 x 2.2 inches)     164
101.0 x 73.0 mm (4.0 x 2.9 inches)    153
83.0 x 60.0 mm (3.3 x 2.4 inches)     153
52.4 x 57.9 mm (2.1 x 2.3 inches)     151
Name: count, dtype: int64

In [35]:
bike_cleaned_df["Fuel system"].value_counts().head(20)

Fuel system
Injection                                                                   3366
Carburettor                                                                 2319
Injection. EFI                                                               453
Injection. Electronic Sequential Port Fuel Injection (ESPFI)                 239
Injection. PGM-FI                                                            229
Injection. Electronic Sequential Port Fuel Injection                         195
Injection. Multipoint sequential electronic fuel injection with SAI          147
Injection. Multipoint sequential electronic fuel injection                   109
Injection. PGM-FI electronic fuel injection                                   80
Injection. Electronic Fuel Injection with dual 45mm throttle body             78
Injection. ESPFI                                                              78
Injection. Fuel Injection with YCC-T and YCC-I                                73
Injection. Closed Loop Sequential Port Fuel Injection                         67
Carburettor. Keihin                                                           64
Carburettor. 30 mm                                                            60
Injection. Electronic intake pipe injection                                   59
Injection. Twin-Bore electronic fuel injection; throttle position sensor      58
Injection. PGM-FI with 34mm throttle bodies                                   52
Carburettor. Dell´Orto PHBN 16                                                50
Carburettor. 17.5 mm                                                          50
Name: count, dtype: int64

In [36]:
bike_cleaned_df["Cooling system"].value_counts().head(20)

Cooling system
Liquid       9448
Air          5548
Oil & air    1044
Name: count, dtype: int64

In [37]:
bike_cleaned_df["Gearbox"].value_counts().head(20)

Gearbox
6-speed      7372
5-speed      4623
Automatic    2649
4-speed      1164
3-speed       159
2-speed        28
1-speed        20
7-speed        13
100-speed      11
10-speed        1
Name: count, dtype: int64

In [38]:
bike_cleaned_df["Transmission type"].value_counts()

Transmission type
Chain   (final drive)                   9969
Belt   (final drive)                    3817
Shaft drive (cardan)   (final drive)    2254
Name: count, dtype: int64

In [39]:
bike_cleaned_df.columns

Index(['Model', 'Category', 'Displacement', 'Engine type', 'Bore x stroke',
       'Fuel system', 'Cooling system', 'Gearbox', 'Transmission type',
       'Fuel capacity', 'Front tire', 'Rear tire', 'Front brakes',
       'Rear brakes'],
      dtype='object')

In [40]:
bike_cleaned_df.drop(columns={"Model","Category"},axis=1,inplace=True)

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\2508234996.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned_df.drop(columns={"Model","Category"},axis=1,inplace=True)

In [41]:
bike_cleaned_df["Front tire"].value_counts(10)

Front tire
120/70-ZR17      0.167893
90/90-21         0.057045
120/70-17        0.038840
80/100-21        0.026683
120/70-12        0.023691
                   ...
22/9-10 (AT)     0.000062
18/7-10 (AT)     0.000062
22/8-10 (AT)     0.000062
16/8-7 (AT)      0.000062
2.25-24          0.000062
Name: proportion, Length: 688, dtype: float64

# feature engineering

In [42]:
# displacement
bike_cleaned_df["Displacement"].value_counts().head(10)

Displacement
249.0 ccm (15.19 cubic inches)    548
124.0 ccm (7.57 cubic inches)     457
125.0 ccm (7.63 cubic inches)     444
49.0 ccm (2.99 cubic inches)      415
998.0 ccm (60.90 cubic inches)    321
449.0 ccm (27.40 cubic inches)    232
649.0 ccm (39.60 cubic inches)    219
999.0 ccm (60.96 cubic inches)    213
49.9 ccm (3.04 cubic inches)      171
798.0 ccm (48.69 cubic inches)    166
Name: count, dtype: int64

In [43]:
bike_cleaned_df["displacement_cc"] = (
    bike_cleaned_df["Displacement"]
    .str.extract(r"(\d+(?:\.\d+)?)\s*ccm", expand=False)
    .astype(float)
)

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\542187127.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned_df["displacement_cc"] = (

In [44]:
bike_cleaned_df["displacement_cc"].isna().sum()

0

In [45]:
bike_cleaned_df["displacement_cc"].value_counts()

displacement_cc
249.0    548
124.0    457
125.0    444
49.0     415
998.0    321
        ...
163.0      1
99.3       1
514.0      1
180.1      1
633.6      1
Name: count, Length: 844, dtype: int64

In [46]:
#engine type: cylinde count
import re

def get_cylinder_count(engine):
    engine = str(engine).lower()

    # Direct numbers: V2, V4, V6, V8
    match = re.search(r'\bv(\d+)\b', engine)
    if match:
        return int(match.group(1))

    # Words
    numbers = {
        "single": 1,
        "twin": 2,
        "three": 3,
        "four": 4,
        "six": 6,
        "eight": 8
    }

    for word, count in numbers.items():
        if word in engine:
            return count

    return np.nan

bike_cleaned_df["cylinder_count"] = bike_cleaned_df["Engine type"].apply(
    get_cylinder_count
)

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\3868695048.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned_df["cylinder_count"] = bike_cleaned_df["Engine type"].apply(

In [47]:
#engine cycle
def get_engine_cycle(engine):
    engine = str(engine).lower()

    if "four-stroke" in engine:
        return 4
    elif "two-stroke" in engine:
        return 2

    return np.nan

bike_cleaned_df["engine_cycle"] = bike_cleaned_df["Engine type"].apply(
    get_engine_cycle
)

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\1859625732.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned_df["engine_cycle"] = bike_cleaned_df["Engine type"].apply(

In [48]:
bike_cleaned_df.head()

,Displacement,Engine type,Bore x stroke,Fuel system,Cooling system,Gearbox,Transmission type,Fuel capacity,Front tire,Rear tire,Front brakes,Rear brakes,displacement_cc,cylinder_count,engine_cycle
0,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,80/90-21,110/80-18,Single disc,Single disc,49.9,1.0,2.0
1,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,130/80-17,130/70-17,Single disc,Single disc,49.9,1.0,2.0
2,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,100/80-17,130/70-17,Single disc,Single disc,49.9,1.0,2.0
5,124.0 ccm (7.57 cubic inches),"Single cylinder, four-stroke",56.5 x 49.5 mm (2.2 x 1.9 inches),Carburettor. Walbro 30 mm,Air,5-speed,Chain (final drive),7.00,100/80-17,130/70-17,Single disc,Single disc. 2-piston caliper,124.0,1.0,4.0
6,233.0 ccm (14.22 cubic inches),"Single cylinder, four-stroke",69.0 x 62.5 mm (2.7 x 2.5 inches),Carburettor. Walbro 30 mm,Oil & air,5-speed,Chain (final drive),7.50,70/100-19,100/100-17,Single disc. 2-piston calipers,Single disc,233.0,1.0,4.0

In [49]:
# bore, stroke 

def extract_bore_stroke(value):
    match = re.search(
        r'(\d+(?:\.\d+)?)\s*x\s*(\d+(?:\.\d+)?)\s*mm',
        str(value),
        re.IGNORECASE
    )

    if match:
        bore = float(match.group(1))
        stroke = float(match.group(2))
        return pd.Series([bore, stroke])

    return pd.Series([np.nan, np.nan])

bike_cleaned_df[["bore_mm", "stroke_mm"]] = bike_cleaned_df["Bore x stroke"].apply(
    extract_bore_stroke
)

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\3461231734.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned_df[["bore_mm", "stroke_mm"]] = bike_cleaned_df["Bore x stroke"].apply(
C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\3461231734.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned_df[["bore_mm", "stroke_mm"]] = bike_cleaned_df["Bore x stroke"].apply(

In [50]:
bike_cleaned_df[["Bore x stroke", "bore_mm", "stroke_mm"]].head(10)

                        Bore x stroke  bore_mm  stroke_mm
0   40.0 x 39.7 mm (1.6 x 1.6 inches)     40.0       39.7
1   40.0 x 39.7 mm (1.6 x 1.6 inches)     40.0       39.7
2   40.0 x 39.7 mm (1.6 x 1.6 inches)     40.0       39.7
5   56.5 x 49.5 mm (2.2 x 1.9 inches)     56.5       49.5
6   69.0 x 62.5 mm (2.7 x 2.5 inches)     69.0       62.5
7   69.0 x 62.5 mm (2.7 x 2.5 inches)     69.0       62.5
8   69.0 x 62.5 mm (2.7 x 2.5 inches)     69.0       62.5
10  56.0 x 49.5 mm (2.2 x 1.9 inches)     56.0       49.5
11  56.0 x 49.5 mm (2.2 x 1.9 inches)     56.0       49.5
12  56.5 x 49.5 mm (2.2 x 1.9 inches)     56.5       49.5

In [51]:
#fuel system 
def simplify_fuel_system(value):
    value = str(value).lower()

    if "injection" in value:
        return "Injection"
    
    elif "carburettor" in value:
        return "Carburettor"
    
    else:
        return "Other"

bike_cleaned_df["fuel_system_type"] = bike_cleaned_df["Fuel system"].apply(
    simplify_fuel_system
)

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\3329230018.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned_df["fuel_system_type"] = bike_cleaned_df["Fuel system"].apply(

In [52]:
bike_cleaned_df["fuel_system_type"].value_counts()

fuel_system_type
Injection      9892
Carburettor    6097
Other            51
Name: count, dtype: int64

In [53]:
bike_cleaned_df["fuel_injection"] = (
    bike_cleaned_df["fuel_system_type"] == "Injection"
).astype(int)

C:\Users\tgbst\AppData\Local\Temp\ipykernel_28864\3126051064.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_cleaned_df["fuel_injection"] = (

In [54]:
bike_cleaned_df.fuel_injection.value_counts()

fuel_injection
1    9892
0    6148
Name: count, dtype: int64

In [55]:
#cooling system 

cooling_encoded = pd.get_dummies(
    bike_cleaned_df["Cooling system"],
    prefix="cooling",
    dtype=int
)

bike_cleaned_df = pd.concat([bike_cleaned_df, cooling_encoded], axis=1)

In [56]:
bike_cleaned_df.head()

,Displacement,Engine type,Bore x stroke,Fuel system,Cooling system,Gearbox,Transmission type,Fuel capacity,Front tire,Rear tire,...,displacement_cc,cylinder_count,engine_cycle,bore_mm,stroke_mm,fuel_system_type,fuel_injection,cooling_Air,cooling_Liquid,cooling_Oil & air
0,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,80/90-21,110/80-18,...,49.9,1.0,2.0,40.0,39.7,Carburettor,0,0,1,0
1,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,130/80-17,130/70-17,...,49.9,1.0,2.0,40.0,39.7,Carburettor,0,0,1,0
2,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,100/80-17,130/70-17,...,49.9,1.0,2.0,40.0,39.7,Carburettor,0,0,1,0
5,124.0 ccm (7.57 cubic inches),"Single cylinder, four-stroke",56.5 x 49.5 mm (2.2 x 1.9 inches),Carburettor. Walbro 30 mm,Air,5-speed,Chain (final drive),7.00,100/80-17,130/70-17,...,124.0,1.0,4.0,56.5,49.5,Carburettor,0,1,0,0
6,233.0 ccm (14.22 cubic inches),"Single cylinder, four-stroke",69.0 x 62.5 mm (2.7 x 2.5 inches),Carburettor. Walbro 30 mm,Oil & air,5-speed,Chain (final drive),7.50,70/100-19,100/100-17,...,233.0,1.0,4.0,69.0,62.5,Carburettor,0,0,0,1

In [57]:
# gear box
import re
import numpy as np

def extract_gears(value):
    match = re.search(r'(\d+)-speed', str(value).lower())

    if match:
        gears = int(match.group(1))

        # Treat unrealistic values as missing
        if 1 <= gears <= 8:
            return gears

    return np.nan

bike_cleaned_df["gear_count"] = bike_cleaned_df["Gearbox"].apply(extract_gears)

In [58]:
bike_cleaned_df["gear_count"].value_counts().sort_index()

gear_count
1.0      20
2.0      28
3.0     159
4.0    1164
5.0    4623
6.0    7372
7.0      13
Name: count, dtype: int64

In [59]:
bike_cleaned_df["is_automatic"] = (
    bike_cleaned_df["Gearbox"]
    .str.lower()
    .str.contains("automatic", na=False)
    .astype(int)
)

In [60]:
bike_cleaned_df.head()

,Displacement,Engine type,Bore x stroke,Fuel system,Cooling system,Gearbox,Transmission type,Fuel capacity,Front tire,Rear tire,...,engine_cycle,bore_mm,stroke_mm,fuel_system_type,fuel_injection,cooling_Air,cooling_Liquid,cooling_Oil & air,gear_count,is_automatic
0,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,80/90-21,110/80-18,...,2.0,40.0,39.7,Carburettor,0,0,1,0,6.0,0
1,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,130/80-17,130/70-17,...,2.0,40.0,39.7,Carburettor,0,0,1,0,6.0,0
2,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,100/80-17,130/70-17,...,2.0,40.0,39.7,Carburettor,0,0,1,0,6.0,0
5,124.0 ccm (7.57 cubic inches),"Single cylinder, four-stroke",56.5 x 49.5 mm (2.2 x 1.9 inches),Carburettor. Walbro 30 mm,Air,5-speed,Chain (final drive),7.00,100/80-17,130/70-17,...,4.0,56.5,49.5,Carburettor,0,1,0,0,5.0,0
6,233.0 ccm (14.22 cubic inches),"Single cylinder, four-stroke",69.0 x 62.5 mm (2.7 x 2.5 inches),Carburettor. Walbro 30 mm,Oil & air,5-speed,Chain (final drive),7.50,70/100-19,100/100-17,...,4.0,69.0,62.5,Carburettor,0,0,0,1,5.0,0

In [61]:
# transmission type
transmission_encoded = pd.get_dummies(
    bike_cleaned_df["Transmission type"],
    prefix="transmission",
    dtype=int
)

bike_cleaned_df = pd.concat([bike_cleaned_df, transmission_encoded], axis=1)

In [62]:
bike_cleaned_df.head()

,Displacement,Engine type,Bore x stroke,Fuel system,Cooling system,Gearbox,Transmission type,Fuel capacity,Front tire,Rear tire,...,fuel_system_type,fuel_injection,cooling_Air,cooling_Liquid,cooling_Oil & air,gear_count,is_automatic,transmission_Belt (final drive),transmission_Chain (final drive),transmission_Shaft drive (cardan) (final drive)
0,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,80/90-21,110/80-18,...,Carburettor,0,0,1,0,6.0,0,0,1,0
1,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,130/80-17,130/70-17,...,Carburettor,0,0,1,0,6.0,0,0,1,0
2,49.9 ccm (3.04 cubic inches),"Single cylinder, two-stroke",40.0 x 39.7 mm (1.6 x 1.6 inches),Carburettor,Liquid,6-speed,Chain (final drive),7.50,100/80-17,130/70-17,...,Carburettor,0,0,1,0,6.0,0,0,1,0
5,124.0 ccm (7.57 cubic inches),"Single cylinder, four-stroke",56.5 x 49.5 mm (2.2 x 1.9 inches),Carburettor. Walbro 30 mm,Air,5-speed,Chain (final drive),7.00,100/80-17,130/70-17,...,Carburettor,0,1,0,0,5.0,0,0,1,0
6,233.0 ccm (14.22 cubic inches),"Single cylinder, four-stroke",69.0 x 62.5 mm (2.7 x 2.5 inches),Carburettor. Walbro 30 mm,Oil & air,5-speed,Chain (final drive),7.50,70/100-19,100/100-17,...,Carburettor,0,0,0,1,5.0,0,0,1,0

In [63]:
#tyre  profiles
def extract_tyre(value):

    match = re.search(
        r'(\d+(?:\.\d+)?)\s*/\s*(\d+(?:\.\d+)?)\s*[-R]\s*(\d+(?:\.\d+)?)',
        str(value),
        re.IGNORECASE
    )

    if match:
        width = float(match.group(1))
        aspect = float(match.group(2))
        rim = float(match.group(3))

        return pd.Series([width, aspect, rim])

    return pd.Series([np.nan, np.nan, np.nan])

In [64]:
bike_cleaned_df[
    ["front_tyre_width", "front_tyre_aspect", "front_tyre_rim"]
] = bike_cleaned_df["Front tire"].apply(extract_tyre)

In [65]:
bike_cleaned_df[
    [
        "Front tire",
        "front_tyre_width",
        "front_tyre_aspect",
        "front_tyre_rim"
    ]
].head(10)

    Front tire  front_tyre_width  front_tyre_aspect  front_tyre_rim
0    80/90-21               80.0               90.0            21.0
1   130/80-17              130.0               80.0            17.0
2   100/80-17              100.0               80.0            17.0
5   100/80-17              100.0               80.0            17.0
6   70/100-19               70.0              100.0            19.0
7   70/100-19               70.0              100.0            19.0
8   70/100-19               70.0              100.0            19.0
10  70/100-19               70.0              100.0            19.0
11  70/100-19               70.0              100.0            19.0
12    2.75-19                NaN                NaN             NaN

In [66]:
# rear profile
bike_cleaned_df[
    ["rear_tyre_width", "rear_tyre_aspect", "rear_tyre_rim"]
] = bike_cleaned_df["Rear tire"].apply(extract_tyre)

In [67]:
bike_cleaned_df[
    [
        "Rear tire",
        "rear_tyre_width",
        "rear_tyre_aspect",
        "rear_tyre_rim"
    ]
].head(10)

      Rear tire  rear_tyre_width  rear_tyre_aspect  rear_tyre_rim
0    110/80-18             110.0              80.0           18.0
1    130/70-17             130.0              70.0           17.0
2    130/70-17             130.0              70.0           17.0
5    130/70-17             130.0              70.0           17.0
6   100/100-17             100.0             100.0           17.0
7   100/100-17             100.0             100.0           17.0
8    90/100-16              90.0             100.0           16.0
10  100/100-17             100.0             100.0           17.0
11  100/100-17             100.0             100.0           17.0
12     3.25-17               NaN               NaN            NaN

In [68]:
bike_cleaned_df["displacement_cc"]

0         49.9
1         49.9
2         49.9
5        124.0
6        233.0
         ...
38396    592.0
38397    592.0
38398    592.0
38399    592.0
38436    249.0
Name: displacement_cc, Length: 16040, dtype: float64

In [69]:
list1=bike_cleaned_df.columns[12:]

In [70]:
list1

Index(['displacement_cc', 'cylinder_count', 'engine_cycle', 'bore_mm',
       'stroke_mm', 'fuel_system_type', 'fuel_injection', 'cooling_Air',
       'cooling_Liquid', 'cooling_Oil & air', 'gear_count', 'is_automatic',
       'transmission_Belt   (final drive)',
       'transmission_Chain   (final drive)',
       'transmission_Shaft drive (cardan)   (final drive)', 'front_tyre_width',
       'front_tyre_aspect', 'front_tyre_rim', 'rear_tyre_width',
       'rear_tyre_aspect', 'rear_tyre_rim'],
      dtype='object')

In [72]:
train_df= bike_cleaned_df[
list1
].copy()

In [73]:
train_df.isnull().sum()

displacement_cc                                         0
cylinder_count                                         62
engine_cycle                                           51
bore_mm                                                 1
stroke_mm                                               1
fuel_system_type                                        0
fuel_injection                                          0
cooling_Air                                             0
cooling_Liquid                                          0
cooling_Oil & air                                       0
gear_count                                           2661
is_automatic                                            0
transmission_Belt   (final drive)                       0
transmission_Chain   (final drive)                      0
transmission_Shaft drive (cardan)   (final drive)       0
front_tyre_width                                     7622
front_tyre_aspect                                    7622
front_tyre_rim                                       7622
rear_tyre_width                                      7702
rear_tyre_aspect                                     7702
rear_tyre_rim                                        7702
dtype: int64

In [75]:
bike_cleaned_df.to_csv("C:\\new project 11\\bike-repo\\data\\motorcycle_cleaned.csv", index=False)

In [77]:
train_df.to_csv("C:\\new project 11\\bike-repo\\data\\motorcycle_features.csv", index=False)

In [78]:
train_df.loc[
    train_df["gear_count"].isna() &
    (train_df["displacement_cc"] <= 250),
    "gear_count"
] = 3

train_df.loc[
    train_df["gear_count"].isna() &
    (train_df["displacement_cc"] > 250) &
    (train_df["displacement_cc"] <= 350),
    "gear_count"
] = 5

train_df.loc[
    train_df["gear_count"].isna() &
    (train_df["displacement_cc"] > 350),
    "gear_count"
] = 6

In [79]:
train_df["gear_count"].isna().sum()

0

In [80]:
train_df.dropna(axis=0,inplace=True)

In [81]:
train_df.head()

,displacement_cc,cylinder_count,engine_cycle,bore_mm,stroke_mm,fuel_system_type,fuel_injection,cooling_Air,cooling_Liquid,cooling_Oil & air,...,is_automatic,transmission_Belt (final drive),transmission_Chain (final drive),transmission_Shaft drive (cardan) (final drive),front_tyre_width,front_tyre_aspect,front_tyre_rim,rear_tyre_width,rear_tyre_aspect,rear_tyre_rim
0,49.9,1.0,2.0,40.0,39.7,Carburettor,0,0,1,0,...,0,0,1,0,80.0,90.0,21.0,110.0,80.0,18.0
1,49.9,1.0,2.0,40.0,39.7,Carburettor,0,0,1,0,...,0,0,1,0,130.0,80.0,17.0,130.0,70.0,17.0
2,49.9,1.0,2.0,40.0,39.7,Carburettor,0,0,1,0,...,0,0,1,0,100.0,80.0,17.0,130.0,70.0,17.0
5,124.0,1.0,4.0,56.5,49.5,Carburettor,0,1,0,0,...,0,0,1,0,100.0,80.0,17.0,130.0,70.0,17.0
6,233.0,1.0,4.0,69.0,62.5,Carburettor,0,0,0,1,...,0,0,1,0,70.0,100.0,19.0,100.0,100.0,17.0

In [82]:
train_df.shape

(8112, 21)

In [84]:
# save final featiured data 
train_df.to_csv("C:\\new project 11\\bike-repo\\data\\final_featured_data.csv", index=False)